# Generated by Django 5.2.4 on 2025-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_remove_customuser_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('supervisor', 'Supervisor')], max_length=20),
        ),
    ]
