# Generated by Django 5.2.4 on 2025-07-31 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_customuser_program_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group_members',
        ),
        migrations.AddField(
            model_name='project',
            name='group_member_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group1_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='group_member_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group2_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='group_member_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group3_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
