# Generated by Django 5.2.4 on 2025-07-31 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_remove_project_group_members_project_group_member_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_member_1',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group1_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
