# Generated by Django 5.2.4 on 2025-08-01 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_alter_project_group_member_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='program',
        ),
        migrations.RemoveField(
            model_name='project',
            name='co_supervisor_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group_member_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group_member_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group_member_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
        ),
    ]
