# Generated by Django 5.2.4 on 2025-08-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_remove_project_description_remove_project_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='submissions/proposals/')),
                ('mis_presentation', models.FileField(blank=True, null=True, upload_to='submissions/mis/')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='submissions/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
