# Generated by Django 5.2.4 on 2025-08-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0012_studentsubmission_delete_projectsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='proposal_presentation',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='report',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='final_presentation',
            field=models.FileField(blank=True, null=True, upload_to='submissions/final_presentations/'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='final_report',
            field=models.FileField(blank=True, null=True, upload_to='submissions/final_reports/'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='mid_presentation',
            field=models.FileField(blank=True, null=True, upload_to='submissions/mid_presentations/'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to='submissions/proposals/'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
