# Generated by Django 5.2.4 on 2025-08-03 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0013_remove_studentsubmission_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, null=True, upload_to='uploads/proposal/')),
                ('srs', models.FileField(blank=True, null=True, upload_to='uploads/srs/')),
                ('mid_presentation', models.FileField(blank=True, null=True, upload_to='uploads/mid_presentation/')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='uploads/final_report/')),
                ('viva_video', models.FileField(blank=True, null=True, upload_to='uploads/viva_video/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
