# Generated by Django 5.2.4 on 2025-08-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0014_studentupload_delete_studentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='uploads/proposals/')),
                ('proposal_uploaded', models.BooleanField(default=False)),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='uploads/presentations/')),
                ('presentation_uploaded', models.BooleanField(default=False)),
                ('final_report_file', models.FileField(blank=True, null=True, upload_to='uploads/final_reports/')),
                ('final_report_uploaded', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentUpload',
        ),
    ]
