# Generated by Django 5.2.4 on 2025-08-03 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0015_studentsubmission_delete_studentupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, null=True, upload_to='submissions/proposals/')),
                ('mid_presentation', models.FileField(blank=True, null=True, upload_to='submissions/mid_presentations/')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='submissions/final_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
