# Generated by Django 5.2.4 on 2025-08-03 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_projectsubmission_delete_studentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('proposal_presentation', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('report', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('mid_presentation', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('final_presentation', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectSubmission',
        ),
    ]
