# Generated by Django 5.2.4 on 2025-08-05 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0020_projectevaluation_delete_supervisorevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectevaluation',
            old_name='supervisor',
            new_name='assigned_supervisor',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='evaluation_comment',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='evaluation_score',
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
