# Generated by Django 5.2.4 on 2025-08-05 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0021_rename_supervisor_projectevaluation_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectevaluation',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='projectevaluation',
            name='assigned_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
