# Generated by Django 5.2.4 on 2025-08-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0023_filesubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesubmission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='status',
        ),
    ]
