# Generated by Django 5.2.4 on 2025-08-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0024_rename_created_at_filesubmission_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectevaluation',
            name='assigned_supervisor',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='FileSubmission',
        ),
        migrations.DeleteModel(
            name='ProjectEvaluation',
        ),
        migrations.DeleteModel(
            name='StudentSubmission',
        ),
    ]
