# Generated by Django 5.2.4 on 2025-08-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0027_projectcomment_projectmeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('proposal', 'Proposal'), ('proposal_report', 'Proposal Report'), ('proposal_presentation', 'Proposal Presentation'), ('final_report', 'Final Report'), ('final_presentation', 'Final Presentation')], max_length=32)),
                ('file', models.FileField(upload_to='submissions/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='final.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'step')},
            },
        ),
    ]
