# Generated by Django 5.2.4 on 2025-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0028_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluation',
            name='final_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=20),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='final_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='final_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='mid_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=20),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='mid_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='mid_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='proposal_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=20),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='proposal_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='proposal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
