# Generated by Django 5.2.4 on 2025-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0029_projectevaluation_final_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevaluation',
            name='final_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectevaluation',
            name='mid_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectevaluation',
            name='proposal_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='projectevaluation',
            unique_together={('project',)},
        ),
    ]
