# Generated by Django 5.2.4 on 2025-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0031_alter_projectevaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectevaluation',
            old_name='final_marks',
            new_name='final_presentation_marks',
        ),
        migrations.RenameField(
            model_name='projectevaluation',
            old_name='final_remarks',
            new_name='final_presentation_remarks',
        ),
        migrations.RenameField(
            model_name='projectevaluation',
            old_name='mid_remarks',
            new_name='mid_presentation_remarks',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='final_decision',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='mid_decision',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='mid_marks',
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='final_presentation_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=10),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='mid_presentation_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=10),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='mid_presentation_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectevaluation',
            name='proposal_decision',
            field=models.CharField(choices=[('pass', 'Pass'), ('revise', 'Revise'), ('fail', 'Fail')], default='pass', max_length=10),
        ),
    ]
