# Generated by Django 5.2.4 on 2025-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0032_rename_final_marks_projectevaluation_final_presentation_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dept_admin', 'Department Admin'), ('student', 'Student'), ('supervisor', 'Supervisor')], max_length=20),
        ),
    ]
