# Generated by Django 5.2.4 on 2025-08-18 09:06

import final.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('final', '0033_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectmeeting',
            options={'ordering': ['-starts_at']},
        ),
        migrations.AlterModelOptions(
            name='submissionfile',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', final.models.CustomUserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='final_custo_role_43674d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department'], name='final_custo_departm_5379e1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['program'], name='final_custo_program_2ac83f_idx'),
        ),
    ]
