# Generated by Django 5.2.4 on 2025-08-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0034_alter_customuser_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectevaluation',
            unique_together={('project', 'evaluator')},
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='final.project'),
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='final_presentation_decision',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='final_presentation_marks',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='final_presentation_remarks',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='mid_presentation_decision',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='mid_presentation_marks',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='mid_presentation_remarks',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='proposal_decision',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='proposal_marks',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='proposal_remarks',
        ),
    ]
