# Generated by Django 5.2.4 on 2025-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0035_alter_projectevaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_presentation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mid_presentation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_presentation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
