# Generated by Django 5.2.4 on 2025-08-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0036_project_final_presentation_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='presentation_place',
            new_name='final_presentation_place',
        ),
        migrations.RemoveField(
            model_name='project',
            name='presentation_at',
        ),
        migrations.AddField(
            model_name='project',
            name='mid_presentation_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_presentation_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
