# Generated by Django 5.2.4 on 2025-08-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0037_rename_presentation_place_project_final_presentation_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='final_custo_program_2ac83f_idx',
        ),
    ]
