# Generated by Django 5.2.4 on 2025-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('final', '0038_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['program'], name='final_custo_program_2ac83f_idx'),
        ),
    ]
