# Generated by Django 5.2.4 on 2025-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0040_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['department', 'program'],
                'unique_together': {('department', 'program')},
            },
        ),
    ]
