# Generated by Django 5.2.4 on 2025-08-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0043_alter_degree_department_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='program',
            new_name='name',
        ),
    ]
