# Generated by Django 5.2.4 on 2025-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0045_remove_department_code_program_delete_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
