# Generated by Django 5.2.4 on 2025-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0046_degree_remove_program_department_delete_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(default='TEMP', max_length=100),
        ),
    ]
