# Generated by Django 5.2.4 on 2025-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0048_alter_customuser_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
